config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount Attachinary::Engine => "/attachinary"

  resources :settings
  resources :services do
  	resources :items
  end

  resources :pages do
		collection do
	    patch :sort
	  end
	end
	get 'admin', to: 'pages#admin'
	root to: 'pages#home'
end

app/models/item.rb
class Item
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :title, type: String
  field :price, type: String

  belongs_to :service, touch: true

  validates :service_id, presence: true
  validates :title, presence: true
end

app/models/service.rb
class Service
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :title, type: String
  field :description, type: String
  field :backgroundcolor, type: String, default: 'grey-theme'
  field :position, type: Integer, default: 0

  has_attachment :image, accept: [:jpg, :png, :gif]
  
  belongs_to :user, touch: true

  has_many :items


  before_validation :save_position
  validates :user_id, presence: true
  validates :title, presence: true

  private
    def save_position
      self.position = (self._index + 1) if self.new_record? and self._index
    end
end

app/models/setting.rb
class Setting
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :title, type: String, default: 'Подорожник'
  field :description, type: String, default: 'СРОЧНАЯ ТЕХНИЧЕСКАЯ ПОМОЩЬ ЗА 20 МИНУТ'
  field :phone, default: '84951111111'
  field :whatsapp
  field :telegram
  field :viber

  field :seotitle, type: String, default: 'Подорожник'
  field :seodescription, type: String, default: 'СРОЧНАЯ ТЕХНИЧЕСКАЯ ПОМОЩЬ ЗА 20 МИНУТ'


  has_attachment :image, accept: [:jpg, :png, :gif]

  validates :title, presence: true
  validates :description, presence: true
  validates :image, presence: true
  validates :phone, presence: true
  validates :seotitle, presence: true
  validates :seodescription, presence: true
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  field :remember_created_at, type: Time

  field :admin, type: Boolean, default: "false"

  has_many :services

  def toggle!(field)
    send "#{field}=", !self.send("#{field}?")
    save :validation => false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
		def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :remember_me])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
      devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password, :admin])
    end
end

app/controllers/items_controller.rb
# encoding: utf-8
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:new, :create, :destroy]

  def new
    @item = Item.new
  end

  def create
    @service = Service.find(params[:service_id])
    @item = @service.items.build(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to @service }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service = Service.find(params[:service_id])
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to service_path(@service) }
      format.json { head :no_content }
    end
  end

  private
    def item_params
      params.require(:item).permit(:title, :price, :service_id)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:admin]
  before_action :admin_user, only: [:admin]

  def home
  	@services = Service.all.order(position: :asc )
  end

  def admin
    @setting = Setting.first
  	@services = Service.all.order(position: :asc )
  end

  def sort
    params[:service].each_with_index do |id, index|
      Service.where(id: id).update_all(position: index + 1)
    end
    head :ok
  end

  private
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/services_controller.rb
  # encoding: utf-8
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:show, :new, :create, :edit, :update, :destroy]

  def show
    @service = Service.find(params[:id])
    @items = @service.items.all
  end

  def new
    @service = Service.new
  end

  def edit
    @service = Service.find(params[:id])
  end

  def create
    @service = current_user.services.build(service_params)
    respond_to do |format|
      if @service.save
        format.html { redirect_to admin_path }
        format.json { render :show, status: :created, location: admin_path }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @service = Service.find(params[:id])
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to admin_path }
        format.json { render :show, status: :ok, location: admin_path }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.json { head :no_content }
    end
  end

  private
    def service_params
      params.require(:service).permit(:title, :description, :image, :user_id, :backgroundcolor, :position)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/settings_controller.rb
  # encoding: utf-8
class SettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:new, :create, :edit, :update]

  def new
    @setting = Setting.new
  end

  def edit
    @setting = Setting.find(params[:id])
  end

  def create
    @setting = Setting.new(setting_params)
    respond_to do |format|
      if @setting.save
        format.html { redirect_to admin_path }
        format.json { render :show, status: :created, location: admin_path }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @setting = Setting.find(params[:id])
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to admin_path }
        format.json { render :show, status: :ok, location: admin_path }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def setting_params
      params.require(:setting).permit(:title, :description, :image, :phone, :telegram, :whatsapp, :viber, :seotitle, :seodescription)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Подорожник</title>
    <meta name="description" content="СРОЧНАЯ ТЕХНИЧЕСКАЯ ПОМОЩЬ ЗА 20 МИНУТ" />
    <meta property="og:title" content="Подорожник" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://podorozhnik-avto.help/" />
    <meta property="og:description" content="СРОЧНАЯ ТЕХНИЧЕСКАЯ ПОМОЩЬ ЗА 20 МИНУТ" />
    <meta property="og:site_name" content="Подорожник" />
    <meta property="og:image" content="<%= asset_path 'carservice.png' %>" />
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>  
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>

    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-KXTV982');</script>
    <!-- End Google Tag Manager -->

  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KXTV982"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/admin.html.erb
<div class="nav">
	<% if Setting.present? %>
		<%= link_to 'Настройки', edit_setting_path(@setting), class: 'btn btn-d' %>
	<% end %>
	<%= link_to 'Выход', destroy_user_session_path, method: :delete, class: 'btn btn-d' %>
</div>
<div class="admin">
	<h4>Категории</h4>
	<div class="margin-top-10">
		<%= link_to 'Добавить категорию', new_service_path, class: 'btn btn-s' %>
	</div>
	<div class="margin-top-20">
		<div id="services" data-url="<%= sort_pages_path %>">
			<% @services.each do |service| %>
				<div id="service_<%= service.id %>">
					<div class="item-inline">
						<div class="item-item coursor item-move">
							<h4>↕</h4>
						</div>
						<div class="item-item admin-service">
							<%= link_to service.title, service, class: 'underline' %></h4>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="header">
	<div class="header-image"><%= cl_image_tag(Setting.first.image.path, { size: '100x100', crop: :thumb, dpr: 3.0 }) %></div>
	<div class="header-title"><%= Setting.first.title %></div>
</div>
<div class="contacts">
	<% if Setting.first.phone.present? %>
		<div class="phone">
			<a href="tel:<%= number_to_phone(Setting.first.phone, area_code: true) %>"><%= number_to_phone(Setting.first.phone, area_code: true) %></a>
		</div>
	<% end %>
	<div class="social-flex">
		<% if Setting.first.whatsapp.present? %>
			<a target="_blank" href="https://wa.me/<%= Setting.first.whatsapp %>">
				<div class="social">
					<%= image_tag 'whatsapp.png', class: 'image' %>
				</div>
			</a>
		<% end %>
		<% if Setting.first.viber.present? %>
			<a target="_blank" href="viber://chat&number=<%= Setting.first.viber %>">
				<div class="social">
					<%= image_tag 'viber.png', class: 'image' %>
				</div>
			</a>
		<% end %>
		<% if Setting.first.telegram.present? %>
			<a target="_blank" href="tg://resolve?domain=<%= Setting.first.telegram %>">
				<div class="social">
					<%= image_tag 'telegram.png', class: 'image' %>
				</div>
			</a>
		<% end %>
	</div>
</div>
<div class="description">
	СРОЧНАЯ ТЕХНИЧЕСКАЯ ПОМОЩЬ ЗА 20 МИНУТ
</div>
<div class="services">
	<%= render @services %>
</div>
<div class="contacts">
	<% if Setting.first.phone.present? %>
		<div class="phone">
			<a href="tel:<%= number_to_phone(Setting.first.phone, area_code: true) %>"><%= number_to_phone(Setting.first.phone, area_code: true) %></a>
		</div>
	<% end %>
	<div class="social-flex">
		<% if Setting.first.whatsapp.present? %>
			<a target="_blank" href="https://wa.me/<%= Setting.first.whatsapp %>">
				<div class="social">
					<%= image_tag 'whatsapp.png', class: 'image' %>
				</div>
			</a>
		<% end %>
		<% if Setting.first.viber.present? %>
			<a target="_blank" href="viber://chat&number=<%= Setting.first.viber %>">
				<div class="social">
					<%= image_tag 'viber.png', class: 'image' %>
				</div>
			</a>
		<% end %>
		<% if Setting.first.telegram.present? %>
			<a target="_blank" href="tg://resolve?domain=<%= Setting.first.telegram %>">
				<div class="social">
					<%= image_tag 'telegram.png', class: 'image' %>
				</div>
			</a>
		<% end %>
	</div>
</div>

app/views/services/_form.html.erb
<%= form_for(@service, html: { role: 'form' }) do |f| %>

  <div class="form-group">
    <h5>Логотип</h5>
    <%= f.attachinary_file_field :image, as: :attachinary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', required: true, placeholder: 'Название' %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, class: 'form-control', placeholder: 'Описание' %>
  </div>

  <div class="form-group">
    <h5>Цвет фона</h5>
    <div class="theme-check">
      <label class="theme-check-label grey-theme">
        <%= f.radio_button :backgroundcolor, 'grey-theme', checked: true, class: 'theme-check-input' %>
        <span class="checkmark"></span>
      </label>

      <label class="theme-check-label green-theme">
        <%= f.radio_button :backgroundcolor, 'green-theme', class: 'theme-check-input' %>
        <span class="checkmark"></span>
      </label>

      <label class="theme-check-label red-theme">
        <%= f.radio_button :backgroundcolor, 'red-theme', class: 'theme-check-input' %>
        <span class="checkmark"></span>
      </label>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.submit 'Сохранить', data: { disable_with: 'Сохраняем...' }, class: 'btn btn-s' %>
    <%= link_to 'Назад', admin_path, class: 'btn btn-d' %>
  </div>
<% end %>

app/views/services/_service.html.erb
<a data-fancybox data-src="#<%= service.id %>" href="javascript:;">
	<div class="item <%= service.backgroundcolor %>">
		<% if service.image.present? %>
			<div class="item-image">
				<%= cl_image_tag(service.image.path, { size: '40x40', crop: :thumb, dpr: 3.0 }) %>
			</div>
		<% end %>
		<div class="item-text white-text"><%= service.title %></div>
	</div>
</a>

<div class="price" id="<%= service.id %>">
	<div class="price-text"><%= service.title %></div>
	<% if service.description.present? %>
		<div class="price-description"><%= service.description %></div>
	<% end %>
	<div class="contacts">
		<% if Setting.first.phone.present? %>
			<div class="phone">
				<a href="tel:<%= number_to_phone(Setting.first.phone, area_code: true) %>"><%= number_to_phone(Setting.first.phone, area_code: true) %></a>
			</div>
		<% end %>
		<div class="social-flex">
			<% if Setting.first.whatsapp.present? %>
				<a target="_blank" href="https://wa.me/<%= Setting.first.whatsapp %>">
					<div class="social">
						<%= image_tag 'whatsapp.png', class: 'image' %>
					</div>
				</a>
			<% end %>
			<% if Setting.first.viber.present? %>
				<a target="_blank" href="viber://chat&number=<%= Setting.first.viber %>">
					<div class="social">
						<%= image_tag 'viber.png', class: 'image' %>
					</div>
				</a>
			<% end %>
			<% if Setting.first.telegram.present? %>
				<a target="_blank" href="tg://resolve?domain=<%= Setting.first.telegram %>">
					<div class="social">
						<%= image_tag 'telegram.png', class: 'image' %>
					</div>
				</a>
			<% end %>
		</div>
	</div>
	<div class="margin-top-20">
		<% service.items.each do |item| %>
			<div class="prices">
				<div class="price-title">
					<%= item.title%>
				</div>
				<div class="price-cost">
					<%= item.price %>₽
				</div>	
			</div>
		<% end %>
	</div>
	<div class="contacts">
		<% if Setting.first.phone.present? %>
			<div class="phone">
				<a href="tel:<%= number_to_phone(Setting.first.phone, area_code: true) %>"><%= number_to_phone(Setting.first.phone, area_code: true) %></a>
			</div>
		<% end %>
		<div class="social-flex">
			<% if Setting.first.whatsapp.present? %>
				<a target="_blank" href="https://wa.me/<%= Setting.first.whatsapp %>">
					<div class="social">
						<%= image_tag 'whatsapp.png', class: 'image' %>
					</div>
				</a>
			<% end %>
			<% if Setting.first.viber.present? %>
				<a target="_blank" href="viber://chat&number=<%= Setting.first.viber %>">
					<div class="social">
						<%= image_tag 'viber.png', class: 'image' %>
					</div>
				</a>
			<% end %>
			<% if Setting.first.telegram.present? %>
				<a target="_blank" href="tg://resolve?domain=<%= Setting.first.telegram %>">
					<div class="social">
						<%= image_tag 'telegram.png', class: 'image' %>
					</div>
				</a>
			<% end %>
		</div>
	</div>
</div>

app/views/services/edit.html.erb
<div class="margin-top-20"></div>
<div class="form-container">
  <h4 class="center">Редактирование</h4>
  <%= render 'form' %>
  <div class="margin-top-20">
  	<%= link_to 'Удалить', @service, class: 'btn btn-w', confirm: 'Вы уверенны?', method: :delete %>
  </div>
</div>

app/views/services/new.html.erb
<div class="margin-top-20"></div>
<h4 class="center">Добавление категории</h4>
<%= render 'form' %>

app/views/services/show.html.erb
<div class="nav">
	<%= link_to 'Редактировать', edit_service_path, class: 'btn btn-d' %>
	<%= link_to 'Назад', admin_path, class: 'btn btn-d' %>
</div>
<div class="admin">
	<h4><%= @service.title %></h4>
	<div class="margin-top-20">
		<% @items.each do |item| %>
			<div class="prices">
				<div class="price-title">
					<%= item.title %>
				</div>
				<div class="price-cost">
					<%= item.price %>
					<%= link_to 'X', service_item_path(@service, item), confirm: 'Вы уверенны?', method: :delete, class: 'btn btn-w btn-small' %>
				</div>
			</div>
		<% end %>
	</div>
	<div class="margin-top-20">
		<%= form_for([@service, Item.new], html: { role: 'form' }) do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: 'form-control', required: true, placeholder: 'Название' %>
      </div>
      <div class="form-group">
        <%= f.text_field :price, class: 'form-control', placeholder: 'Стоимость' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Добавить услугу', data: { disable_with: 'Сохраняем...' }, class: 'btn btn-s' %>
      </div>
    <% end %>
	</div>
</div>

app/views/settings/_form.html.erb
<%= form_for(@setting, html: { role: 'form' }) do |f| %>
  <div class="form-group">
    <h5>Логотип</h5>
    <%= f.attachinary_file_field :image, as: :attachinary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <h5>Название сайта</h5>
    <%= f.text_field :title, class: 'form-control', required: true, placeholder: 'Название' %>
  </div>
  <div class="form-group">
    <h5>Описание сайта</h5>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Описание' %>
  </div>

  <div class="form-group">
    <h5>Телефонный номер</h5>
    <%= f.text_field :phone, class: 'form-control', placeholder: 'Телефонный номер' %>
    <small>Номер телефона: +7495111111</small>
  </div>

  <div class="form-group">
    <h5>Whatsapp</h5>
    <%= f.text_field :whatsapp, class: 'form-control', placeholder: 'WhatsAPP' %>
    <small>Номер телефона: +7495111111</small>
  </div>

  <div class="form-group">
    <h5>Viber</h5>
    <%= f.text_field :viber, class: 'form-control', placeholder: 'Viber' %>
    <small>Номер телефона: +7495111111</small>
  </div>

  <div class="form-group">
    <h5>Telegram</h5>
    <%= f.text_field :telegram, class: 'form-control', placeholder: 'Telegram' %>
    <small>Имя пользователя: username</small>
  </div>
  
  <div class="form-group">
    <%= f.submit 'Сохранить', data: { disable_with: 'Сохраняем...' }, class: 'btn btn-s' %>
    <%= link_to 'Назад', admin_path, class: 'btn btn-d' %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<div class="margin-top-20"></div>
<h4 class="center">Настройки</h4>
<%= render 'form' %>

app/views/settings/new.html.erb
<div class="margin-top-20"></div>
<h4 class="center">Настройки</h4>
<%= render 'form' %>